# Lindholmen Dataset

The Lindholmen dataset is used to source activity diagrams to redraw as sketch.

## Libraries

In [1]:
import pandas as pd
from numpy import nan
from urllib.parse import urlparse
import requests
from tqdm import tqdm
import time

## Methods

In [2]:
def get_url_extension(url):
    if pd.isna(url):
        return ''
    # Parse the URL and get the path
    path = urlparse(str(url)).path
    # Extract extension from path
    if '.' in path:
        return path.split('.')[-1].lower()
    return ''

## Code

Load CSV file

In [3]:
dataset = pd.read_csv("UMLFiles_List_V2.0.csv")

In [4]:
dataset.columns

Index(['Project', 'Model Link - Github'], dtype='str')

In [5]:
dataset.rename(columns={'Model Link - Github': 'Link'}, inplace=True)

Isolate username and project. Extract file extension

In [6]:
dataset['Username'] = dataset['Project'].str.split("/").str[0]
dataset['Repository'] = dataset['Project'].str.split("/").str[1]
dataset['File_Extension'] = dataset['Link'].apply(get_url_extension)

Reorder columns

In [7]:
dataset = dataset[['Username', 'Repository', 'Project', 'Link', 'File_Extension']]

Inspect dataset sample

In [8]:
dataset

,Username,Repository,Project,Link,File_Extension
0,0-complexity,ovcdoc_public,0-complexity/ovcdoc_public/,https://www.github.com/0-complexity/ovcdoc_pub...,png
1,0003088,libelektra-qt-gui-test,0003088/libelektra-qt-gui-test/,https://www.github.com/0003088/libelektra-qt-g...,xmi
2,00s,deadman,00s/deadman/,https://www.github.com/00s/deadman/tree/master...,png
3,01db0y,ImageUploader,01db0y/ImageUploader/,https://www.github.com/01db0y/ImageUploader/tr...,png
4,01db0y,ShareIt,01db0y/ShareIt/,https://www.github.com/01db0y/ShareIt/tree/mas...,png
...,...,...,...,...,...
93602,yotomyoto,301_assignment1,yotomyoto/301_assignment1/,https://www.github.com/yotomyoto/301_assignmen...,svg
93603,zeronero13,af6,zeronero13/af6/,https://www.github.com/zeronero13/af6/tree/mas...,svg
93604,zeronero13,happehardver,zeronero13/happehardver/,https://www.github.com/zeronero13/happehardver...,svg
93605,Akshit-,ClientServerCommunication,Akshit-/ClientServerCommunication/,https://www.github.com/Akshit-/ClientServerCom...,png
93606,Akshit-,ClientServerCommunication,Akshit-/ClientServerCommunication/,https://www.github.com/Akshit-/ClientServerCom...,png

Inspect file extensions

In [9]:
dataset['File_Extension'].unique()

<ArrowStringArray>
[                            'png',                             'xmi',
                             'uml',                             'jpg',
                             'svg',                            'jpeg',
                             'gif',                             'bmp',
                                '',         'resources/sets/set3/005',
 'com/railsforcharity/spokenvote/',                               '2',
               'com/tree/master/c']
Length: 13, dtype: str

Remove all files that does not have the extension "png", "jpg", "svg", "jpeg", "gif" or "bmp"

In [10]:
dataset = dataset[dataset['File_Extension'].isin(['png', 'jpg', 'svg', 'jpeg', 'gif', 'bmp'])].reset_index(drop=True)

In [11]:
dataset

,Username,Repository,Project,Link,File_Extension
0,0-complexity,ovcdoc_public,0-complexity/ovcdoc_public/,https://www.github.com/0-complexity/ovcdoc_pub...,png
1,00s,deadman,00s/deadman/,https://www.github.com/00s/deadman/tree/master...,png
2,01db0y,ImageUploader,01db0y/ImageUploader/,https://www.github.com/01db0y/ImageUploader/tr...,png
3,01db0y,ShareIt,01db0y/ShareIt/,https://www.github.com/01db0y/ShareIt/tree/mas...,png
4,0416354917,COMP6442,0416354917/COMP6442/,https://www.github.com/0416354917/COMP6442/tre...,png
...,...,...,...,...,...
57828,yotomyoto,301_assignment1,yotomyoto/301_assignment1/,https://www.github.com/yotomyoto/301_assignmen...,svg
57829,zeronero13,af6,zeronero13/af6/,https://www.github.com/zeronero13/af6/tree/mas...,svg
57830,zeronero13,happehardver,zeronero13/happehardver/,https://www.github.com/zeronero13/happehardver...,svg
57831,Akshit-,ClientServerCommunication,Akshit-/ClientServerCommunication/,https://www.github.com/Akshit-/ClientServerCom...,png
57832,Akshit-,ClientServerCommunication,Akshit-/ClientServerCommunication/,https://www.github.com/Akshit-/ClientServerCom...,png

Get number of unique projects

In [12]:
dataset['Project'].nunique()

18687

Get only links with 'class' in 'Link' path

In [13]:
dataset[dataset['Link'].str.contains(
    r'(activity)', 
    case=False, 
    na=False, 
    regex=True
)]['Link'].to_csv('activity_links.csv', index=False)

C:\Users\Simon\AppData\Local\Temp\ipykernel_24184\1609874123.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  dataset[dataset['Link'].str.contains(